name: Node.js CI

on: [push]

jobs:
  test:
    name: Test Express server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        working-directory: "server"
        run: npm i
      - name: Test
        working-directory: "server"
        run: npm test
